### ISSUE TITLE
Config::Tiny

### ISSUE THREAD

**Issue by ap** [perlancar/perl-Bencher-Scenario-INIParsingModules#1]
Should be included.

(Maybe AppConfig too, though I guess it depends. It will parse INI files but supports some extensions that go beyond INI.)

**Comment by perlancar** [comment]
I've added Config::Tiny (commit 45f2065). Not adding AppConfig for now; it requires all parameters to be defined first.

**Comment by ap** [comment]
Oh, I see. I’ve dealt with it from a user perspective but haven’t written code that uses it, so I was aware that its syntax is close to INI but not what its API looks like. Never mind then.
